---

- name: Install Apache
  hosts: application_servers
  become: true

  tasks:

    - name: Install Apache
      ansible.builtin.package:
        name:
          - httpd
          - httpd-devel
        state: present

    - name: Copy configuration files
      ansible.builtin.copy:
        src: "{{ item['src'] }}"
        dest: "{{ item['dest'] }}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: httpd.conf
          dest: /etc/httpd/conf/httpd.conf
        - src: httpd-vhosts.conf
          dest: /etc/httpd/conf/httpd-vhosts.conf

    - name: Make sure Apache is started now and at boot.
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: false
