---

- name: Myhosts
  hosts: localhost
  connection: local
  gather_facts: false
  # become: true

  vars_files:
    - vars/api_key.yml

  tasks:

    - name: Echo the API key which was injected into the env.
      ansible.builtin.shell: echo $API_KEY
      environment:
        API_KEY: "{{ myapp_api_key }}"
      register: echo_result
      changed_when: echo_result.rc != 0

    - name: Show the result.
      ansible.builtin.debug:
        var: echo_result.stdout
